# true：主动索要Proxy-Authorization，可能会被探测到是代理服务器。除非通过Chrom插件SwitchyOmega使用该代理，否则不建议设置为true
# false: 不索要Proxy-Authorization
ask4Authcate=false

# http代理部分设置
# true:开启，false:不开启
http.enable=true         
# http代理的端口
http.port=4888
# http代理的用户名和密码，逗号分割多个用户。不设置则不启用鉴权
#http.auth=user1:passwd,user2:passwd

# https代理部分设置
# true:开启，false:不开启
https.enable=true
# https代理的端口
https.port=4843
# http代理的用户名和密码，逗号分割多个用户。不设置则不启用鉴权
#https.auth=user1:passwd,user2:passwd
# TLS证书的fullchain（从CA证书到域名证书）
https.fullchain.pem=/root/HttpProxy/cert.pem
# TLS证书的私钥
https.privkey.pem=/root/HttpProxy/private.key