# true 则可能被探测到是https代理
ask4Authcate=false
# http代理配置
http.enable=true
http.port=4888
## 白名单模式优先级大于auth模式，即配置了白名单则只有白名单内的域名才可通过
#http.proxy.white.domain=github.com
#http.auth=arloor:httpforarloor
# over Tls配置
https.enable=true
https.port=4843
#https.auth=arloor:httpforarloor
https.fullchain.pem=/root/HttpProxy/cert.pem
https.privkey.pem=/root/HttpProxy/private.key



